### ISSUE TITLE
instance Representable f => Representable (Reverse f)?

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/adjunctions#25]
Is there a valid `Representable` instance for [`Reverse`](https://hackage.haskell.org/package/transformers-0.5.2.0/docs/Data-Functor-Reverse.html)?

```haskell
instance Representable f => Representable (Reverse f) where
  type Rep (Reverse f) = Rep f
  tabulate = Reverse . tabulate
  index (Reverse f) i = index f i
```

gives the same result for these two expressions

```haskell
>>> (!) = index; infixl 6 ! 
>>> V3 'x' 'y' 'z' ! E _x
'x'
>>> Reverse (V3 'x' 'y' 'z') ! E _x
'x'
```

**Comment by Icelandjack** [comment]
I was toying around with defining a queue as `Product V3 (Reverse V3)`.

**Comment by RyanGlScott** [comment]
Sounds reasonable to me.
