### ISSUE TITLE
Add withIndex helper function?

### ISSUE THREAD

**Issue by ChrisPenner** [ekmett/adjunctions#40]
Hey there; this is a nicely thought out and very elegant lib!

I've found the following functions useful:

```haskell
withIndex :: (Eq (Rep f), Representable f) => Rep f -> (a -> a) -> f a -> f a
setIndex :: (Eq (Rep f), Representable f) => Rep f -> a -> f a -> f a
```

With the relatively inefficient implementations:

```haskell
withIndex :: (Eq (Rep f), Representable f) => Rep f -> (a -> a) -> f a -> f a
withIndex ind g fa = tabulate $ \rep ->
      let existing = index fa rep
       in if rep == ind then g existing
          else existing

setIndex :: (Eq (Rep f), Representable f) => Rep f -> a -> f a -> f a
setIndex ind = withIndex ind . const
```

If these would be of interest to others I can write up a PR. Let me know what you think;

**Comment by Icelandjack** [comment]
Is this not a lens

```haskell
_Rep :: (Representable r, Eq (Rep r)) => Rep r -> Lens' (r a) a 
_Rep rep f ra = f (index ra rep) <&> \a -> 
  tabulate $ \case
    ((== rep) -> True) -> a
    rep'               -> index ra rep'
```

`withIndex` & `setIndex` can be defined in terms of it 

```haskell
withIndex :: (Eq (Rep f), Representable f) => Rep f -> (a -> a) -> f a -> f a
withIndex rep = over (_Rep rep)

setIndex :: (Eq (Rep f), Representable f) => Rep f -> a -> f a -> f a
setIndex rep = set (_Rep rep)
```

**Comment by Icelandjack** [comment]
this seems exactly like what @treeowl proposes in #30

**Comment by ChrisPenner** [comment]
@Icelandjack Yup I'd be totally fine with either _Rep or IxSure being added. I can write my own lenses for Representable functor of course, but it'd be nice to at least have a unifying class like IxSure to put things. That said, all the general implementations of IxSure are extremely inefficient, so  that kinda sucks.

**Comment by ChrisPenner** [comment]
I recently discovered that it's trivial to instance the `*WithIndex` typeclasses using helpers from this lib.

E.g.

```haskell
instance FunctorWithIndex MyRepType MyRepresentableFunctor where
  imap = imapRep

instance FoldableWithIndex MyRepType MyRepresentableFunctor where
  ifoldMap = ifoldMapRep

instance TraversableWithIndex MyRepType MyRepresentableFunctor where
  itraverse = itraverseRep
```

Then the indexed lenses provide the functionality I want quite nicely; e.g. the `index` lens works great!
