### ISSUE TITLE
representable-functors package

### ISSUE THREAD

**Issue by siddhanathan** [ekmett/adjunctions#44]
I'm confused on why there is a Representable class in both representable-functors and adjunctions. Does the version here supersede the version in representable-functors? If yes, can the documentation in both packages be updated to reflect that?

**Comment by sjoerdvisscher** [comment]
It says so right at the top: https://hackage.haskell.org/package/representable-functors

**Comment by siddhanathan** [comment]
Whoops. Sorry, missed it.
